import {useState} from 'react';
import {Dialog,FloorPlan} from '../Forms';

export function Link({to,onNavigate,children,className=''}){return <a className={className} href={to} onClick={e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();onNavigate(to);}}>{children}</a>;}
export function PageTitle({eyebrow,title,italic}){return <section className="af-page-title af-ivory" data-scene="none" data-ui="light"><span className="af-small">Afrah / {eyebrow}</span><h1>{title}{italic&&<><br/><em>{italic}</em></>}</h1></section>;}
export function NextChapter({label,to,onNavigate,onViewing}){return <section className="af-next" data-scene="none"><span className="af-small">Continue the story</span><Link to={to} onNavigate={onNavigate}>{label}<span>↗</span></Link><button className="af-text-link" onClick={onViewing}>Arrange a viewing ↗</button></section>;}

export function ResidenceExperience({Stage,floor,setFloor,hover,onViewing,compact=false}){
  const [unit,setUnit]=useState('A'),[plan,setPlan]=useState(false);
  const number=String(floor).padStart(2,'0')+unit,area=unit==='A'?142:158;
  return <><Stage scene="residences" id={compact?'choose':'residences'} height={compact?170:145} className="af-residence-stage"><div className="af-residence-panel"><span className="af-small">{compact?'06 / Find your place':'The residences'}</span><h2>Your<br/><em>perspective.</em></h2><div className="af-floor-control"><button aria-label="Previous floor" disabled={floor===1} onClick={()=>setFloor(floor-1)}>−</button><label htmlFor={compact?'floor-home':'floor-page'}>Floor <select aria-label="Floor" id={compact?'floor-home':'floor-page'} value={floor} onChange={e=>setFloor(Number(e.target.value))}>{Array.from({length:43},(_,i)=>i+1).map(n=><option key={n} value={n}>{String(n).padStart(2,'0')}</option>)}</select></label><button aria-label="Next floor" disabled={floor===43} onClick={()=>setFloor(floor+1)}>+</button></div><div className="af-unit-options" aria-label="Residence"><button aria-pressed={unit==='A'} onClick={()=>setUnit('A')}>Residence A</button><button aria-pressed={unit==='B'} onClick={()=>setUnit('B')}>Residence B</button></div><dl className="af-residence-data"><div><dt>Residence</dt><dd>{number}</dd></div><div><dt>Area</dt><dd>{area} m²</dd></div><div><dt>Bedrooms</dt><dd>2</dd></div><div><dt>Orientation</dt><dd>{unit==='A'?'South east':'South west'}</dd></div></dl><button className="af-line-link" onClick={()=>setPlan(true)}>Explore the plan <span>↗</span></button><button className="af-line-link" onClick={()=>onViewing(number)}>Enquire about this residence <span>↗</span></button><p className="af-note">Illustrative layouts and dimensions.</p></div><div className="af-floor-hint"><span className="af-small">{hover>0?`Floor ${String(hover).padStart(2,'0')} — click to select`:'Explore the building / Select a floor'}</span></div></Stage>{plan&&<Dialog title={`Residence ${number} floor plan`} onClose={()=>setPlan(false)} className="af-plan-dialog"><span className="af-small">Floor {floor} / {area} m²</span><h2>Residence {number}</h2><FloorPlan unit={number}/><p className="af-note">An illustrative two-bedroom plan. Final layouts are subject to confirmation.</p><button className="af-line-link" onClick={()=>{setPlan(false);onViewing(number);}}>Arrange a viewing ↗</button></Dialog>}</>;
}

const places=[{name:'The gardens',copy:'A green edge. A slower rhythm.',x:710,y:175},{name:'The neighbourhood',copy:'Everyday life, close to home.',x:240,y:335},{name:'The arrival',copy:'A considered welcome.',x:535,y:420}];
export function PlaceMap({full=false,onNavigate}){const [selected,setSelected]=useState(0);return <section className={`af-place af-ivory ${full?'full':''}`} data-scene="none" data-ui="light"><div className="af-place-title"><span className="af-small">{full?'The setting':'07 / The setting'}</span><h2>A world<br/><em>around you.</em></h2><p>{places[selected].copy}</p>{!full&&<Link className="af-text-link" to="/place" onNavigate={onNavigate}>Explore the place ↗</Link>}</div><div className="af-map"><svg viewBox="0 0 960 640" role="img" aria-label="Illustrative Afrah neighbourhood diagram showing the gardens, neighbourhood and arrival"><g className="map-roads" fill="none" stroke="currentColor"><path d="M0 190L960 435M0 450L960 165M310 0L630 640M720 0L345 640" strokeWidth="18"/><path d="M0 190L960 435M0 450L960 165M310 0L630 640M720 0L345 640" strokeWidth="1"/></g><g className="map-blocks" fill="currentColor">{[[110,200,88,70],[215,110,75,80],[380,70,66,100],[730,370,85,65],[670,465,88,80],[380,450,75,105],[175,445,100,65],[80,315,70,70],[710,260,95,50]].map(([x,y,w,h],i)=><rect key={i} x={x} y={y} width={w} height={h} transform={`rotate(-16 ${x} ${y})`}/>)}</g><g className="map-garden" fill="none" stroke="currentColor">{Array.from({length:12},(_,i)=><ellipse key={i} cx={700+(i%4)*33} cy={100+Math.floor(i/4)*36} rx="17" ry="23"/>)}</g><g className="map-afrah"><path d="M455 235L488 224L517 238L482 250Z"/><path d="M455 235V352L482 368V250Z" opacity=".7"/><path d="M482 250L517 238V355L482 368Z" opacity=".9"/><path d="M525 275L551 266L573 278L547 288Z"/><path d="M525 275V354L547 366V288Z" opacity=".7"/><path d="M547 288L573 278V357L547 366Z" opacity=".9"/></g><text x="460" y="401">AFRAH</text>{places.map((v,i)=><g className={`map-marker ${selected===i?'selected':''}`} key={v.name} role="button" tabIndex="0" aria-label={v.name} onClick={()=>setSelected(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(i);}}} transform={`translate(${v.x} ${v.y})`}><circle r="21"/><text textAnchor="middle" dy="4">0{i+1}</text></g>)}</svg><div className="af-map-legend">{places.map((v,i)=><button key={v.name} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>0{i+1}</span>{v.name}</button>)}</div><span className="af-note">An illustrative setting. Not a geographic map.</span></div></section>;}

export function MaterialPair(){return <section className="af-material-pair af-ivory" data-scene="none" data-ui="light"><div><span className="af-small">The interior language</span><h2>Soft light.<br/><em>Honest materials.</em></h2><p>Stone, timber and a little stillness.</p></div><figure><img loading="lazy" src="/cinematic/images/lounge.webp" alt="An intimate interior with sculptural furniture, timber and warm natural tones"/><figcaption>01 / The living room</figcaption></figure><figure><img loading="lazy" src="/cinematic/images/interior.webp" alt="Sunlight across an ivory living space with linen upholstery and timber details"/><figcaption>02 / Light, throughout</figcaption></figure></section>;}

export function ChapterPage({path,Stage,Editorial,onNavigate,onViewing,floor,setFloor,hover}){
  if(path==='/residences')return <><ResidenceExperience Stage={Stage} floor={floor} setFloor={setFloor} hover={hover} onViewing={onViewing}/><section className="af-residence-intro af-ivory" data-scene="none" data-ui="light"><span className="af-small">Space, considered</span><h2>Life takes<br/><em>its own shape.</em></h2><p>Explore a floor. Find your perspective.<br/>Arrange a personal introduction.</p></section><NextChapter label="The interiors" to="/interiors" onNavigate={onNavigate} onViewing={onViewing}/></>;
  if(path==='/place')return <><PageTitle eyebrow="Place" title="Connected." italic="At ease."/><PlaceMap full/><Editorial title="A green edge." number="01" image="/cinematic/images/morning.webp" line="An invitation to slow down." link="/landscape" onNavigate={onNavigate}/><NextChapter label="The residences" to="/residences" onNavigate={onNavigate} onViewing={onViewing}/></>;
  if(path==='/interiors')return <><PageTitle eyebrow="Interiors" title="A quieter" italic="kind of living."/><section className="af-full-image" data-scene="none"><img src="/cinematic/images/interior.webp" alt="A bright, calm residential interior with timber and natural linen"/></section><MaterialPair/><Stage scene="object" height={240}><div className="af-caption"><span className="af-small">Stone / Glass / Light</span><h2>A dialogue<br/><em>of materials.</em></h2></div></Stage><NextChapter label="The landscape" to="/landscape" onNavigate={onNavigate} onViewing={onViewing}/></>;
  if(path==='/landscape')return <><PageTitle eyebrow="Landscape" title="Room" italic="to breathe."/><section className="af-full-image af-landscape-image" data-scene="none"><img src="/cinematic/images/morning.webp" alt="Sunlight falling through a quiet green landscape"/><span className="af-small">Morning, unhurried.</span></section><section className="af-residence-intro af-ivory" data-scene="none" data-ui="light"><span className="af-small">Between home and horizon</span><h2>Life.<br/><em>Outside.</em></h2><p>Planted terraces. Quiet corners.<br/>A daily connection to the open air.</p></section><PlaceMap onNavigate={onNavigate}/><NextChapter label="The architecture" to="/architecture" onNavigate={onNavigate} onViewing={onViewing}/></>;
  return <><PageTitle eyebrow="Architecture" title="A sense" italic="of presence."/><Stage scene="building" height={360}><div className="af-caption"><span className="af-small">Architecture / Afrah</span><h2>Drawn<br/><em>to the light.</em></h2></div></Stage><section className="af-architecture-notes af-ivory" data-scene="none" data-ui="light"><span className="af-small">Three elements. One expression.</span>{[['01','Stone','Depth, rhythm, permanence.'],['02','Glass','Light and changing reflections.'],['03','Terraces','A private piece of the outside.']].map(([n,title,copy])=><article key={n}><span className="af-small">{n}</span><h2>{title}</h2><p>{copy}</p></article>)}</section><Stage scene="tunnel" height={290}><div className="af-caption"><span className="af-small">Structure becomes experience</span><h2>A passage<br/><em>through Afrah.</em></h2></div></Stage><NextChapter label="The interiors" to="/interiors" onNavigate={onNavigate} onViewing={onViewing}/></>;
}
