import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowDown,ArrowUpRight,ArrowRight,Plus,Minus,ChevronLeft,ChevronRight,Play} from 'lucide-react';
import {Link,useStory} from './Context';
const Sculpture=lazy(()=>import('../scene/CompositeSculpture'));
export function Label({children,className='',...props}){return <span className={`s-label ${className}`} {...props}>{children}</span>}
export function TextLink({to,children,className=''}){return <Link to={to} className={`s-text-link ${className}`}><span>{children}</span><ArrowUpRight size={20}/></Link>}
export function Media({src,alt='',className='',eager=false}){return <figure className={`s-media ${className}`}><img src={src} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined}/></figure>}
export function SectionHead({number,children,aside}){return <div className="s-section-head"><Label>[ {number} ] {children}</Label>{aside&&<Label>{aside}</Label>}</div>}
export function Statement({label,children,dark=false}){return <section className={`s-statement s-pad ${dark?'s-dark':''}`}><Label>{label}</Label><p className="s-word-reveal">{children.split(' ').map((word,i)=><span key={i}>{word}{' '}</span>)}</p></section>}
export function Editorial({number,title,text,image,alt,link,reverse=false,dark=false}){return <section className={`s-editorial s-pad ${reverse?'reverse':''} ${dark?'s-dark':''}`}><Media src={image} alt={alt} className="s-image-drift"/><div className="s-editorial-copy"><Label>[ {number} ] / A DIFFERENT NATURE</Label><h2 className="s-reveal">{title}</h2><p>{text}</p>{link&&<TextLink to={link[0]}>{link[1]}</TextLink>}</div></section>}
export function PageHero({number,title,subtitle,image}){return <section className="s-page-hero"><Media src={image} alt={subtitle} eager/><div className="s-hero-shade"/><div className="s-page-hero-copy s-pad"><Label>AFRAH / CHAPTER {number}</Label><h1 tabIndex="-1">{title}</h1><div><p>{subtitle}</p><a href="#chapter-start" className="s-circle" aria-label="Explore this chapter"><ArrowDown/></a></div></div></section>}
export function SculptureHero({vision=false}){
 const ref=useRef(),progress=useRef(0);const [mount,setMount]=useState(false);
 useEffect(()=>{const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){setMount(true);io.disconnect()}},{rootMargin:'300px'});io.observe(ref.current);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const t=gsap.timeline({scrollTrigger:{trigger:ref.current,start:'top top',end:'bottom bottom',scrub:1.2,onUpdate:s=>progress.current=s.progress}});t.to('.s-sculpture-title',{yPercent:-22,opacity:0,duration:.7},0).fromTo('.s-sculpture-second',{opacity:0,y:60},{opacity:1,y:0,duration:.5},.45);});return()=>{io.disconnect();mm.revert()}},[]);
 return <section ref={ref} className="s-sculpture-track"><div className="s-sculpture-pin"><div className="s-coordinate-grid"/>{mount&&<Suspense fallback={<img className="s-sculpture-fallback" src="/composites/materials.jpg" alt=""/>}><Sculpture progress={progress} tone="silver" variant={vision?'tunnel':'shape'}/></Suspense>}<div className="s-sculpture-top s-pad"><Label>{vision?'01 / THE VISION':'AN EXPLORATION OF LIFE & SPACE'}</Label><Label>FORM. NATURE. HUMAN.</Label></div><h1 className="s-sculpture-title" tabIndex="-1">{vision?<>BETWEEN<br/>TWO<br/>WORLDS.</>:<>A DIFFERENT<br/>NATURE.</>}</h1><div className="s-sculpture-second"><Label>[ THE AFRAH IDEA ]</Label><h2>LESS NOISE.<br/>MORE LIFE.</h2><p>A place where the energy of the city<br/>meets a quieter way of living.</p></div><div className="s-sculpture-bottom s-pad"><span className="s-sculpture-wordmark">AFRAH<span>®</span></span><p>Architecture with presence.<br/>A life with possibility.</p><a href="#chapter-start" className="s-scroll-cue"><span>SCROLL TO<br/>UNFOLD THE STORY</span><ArrowDown size={18}/></a></div></div></section>
}
export function BuildingReveal(){const [night,setNight]=useState(false);return <section className={`s-building-reveal ${night?'is-night':''}`}><img className="s-building-sky" src="/story/likova-sky.webp" alt="" loading="lazy"/><div className="s-building-heading s-pad"><Label>[ 02 / ARCHITECTURE IN MOTION ]</Label><h2>A NEW<br/>PERSPECTIVE.</h2></div><img className="s-layer-building" src="/story/likova-building.webp" alt="Stepped glazed building rising into the sky" loading="lazy"/><img className="s-layer-lights" src="/story/likova-lights.webp" alt="" loading="lazy"/><div className="s-building-bottom s-pad"><div className="s-segmented" aria-label="Building lighting"><button aria-pressed={!night} onClick={()=>setNight(false)}>DAY</button><button aria-pressed={night} onClick={()=>setNight(true)}>EVENING</button></div><TextLink to="/architecture">Explore the architecture</TextLink></div></section>}
export function NextChapter({to,number,title,image}){return <Link to={to} className="s-next-chapter"><Media src={image}/><div className="s-next-shade"/><div className="s-pad"><Label>NEXT CHAPTER / {number}</Label><h2>{title}<ArrowUpRight/></h2><span className="s-label">CONTINUE THE STORY</span></div></Link>}
export function Accordion({items}){const[open,setOpen]=useState(0);return <div className="s-accordion">{items.map(([title,text],i)=><div className={open===i?'is-open':''} key={title}><button aria-expanded={open===i} aria-controls={`detail-${i}`} onClick={()=>setOpen(open===i?-1:i)}><span className="s-label">0{i+1}</span><span>{title}</span>{open===i?<Minus/>:<Plus/>}</button><div id={`detail-${i}`} hidden={open!==i}><p>{text}</p></div></div>)}</div>}
export function Gallery({items,title='A closer look.'}){const [index,setIndex]=useState(0),start=useRef(null);return <section className="s-gallery s-pad"><div className="s-gallery-top"><h2>{title}</h2><div><Label>{String(index+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</Label><button className="s-circle" aria-label="Previous image" onClick={()=>setIndex((index+items.length-1)%items.length)}><ChevronLeft/></button><button className="s-circle" aria-label="Next image" onClick={()=>setIndex((index+1)%items.length)}><ChevronRight/></button></div></div><div className="s-gallery-frame" onTouchStart={e=>start.current=e.touches[0].clientX} onTouchEnd={e=>{if(start.current!==null&&Math.abs(e.changedTouches[0].clientX-start.current)>40)setIndex((index+(e.changedTouches[0].clientX<start.current?1:items.length-1))%items.length);start.current=null}}>{items.map(([src,caption],i)=><figure className={index===i?'active':''} key={src} aria-hidden={index!==i}><img src={src} alt={caption} loading="lazy"/></figure>)}</div><div className="s-gallery-caption" aria-live="polite"><Label>{items[index][1]}</Label><Label>AFRAH / SPACES TO INHABIT</Label></div></section>}
export function FilmSection(){const{setFilm}=useStory();return <section className="s-film"><Media src="/media/living.webp" alt="A sunlit home"/><div className="s-film-shade"/><div className="s-pad"><Label>A FILM ABOUT FEELING AT HOME</Label><h2>LIFE,<br/>UNHURRIED.</h2><button className="s-film-play" onClick={()=>setFilm(true)}><span className="s-circle"><Play size={19}/></span><span>PLAY THE FILM<br/><small>00:18 / AFRAH</small></span></button></div></section>}
const materialItems=[['Stone','Calm, grounded, enduring.','A quiet foundation for the spaces we pass through every day.','/era/arch.webp'],['Metal','A fine line of light.','Reflections bring depth to edges, entrances and the details we touch.','/story/idea-detail.webp'],['Glass','A closer connection.','Framed views and changing light connect a room to the world outside.','/story/idea-space.webp']];
export function Materials(){const [index,setIndex]=useState(0);return <section className="s-materials s-pad s-dark"><SectionHead number="04" aside="THE MATERIAL LIBRARY">MATTER, MADE MEANINGFUL</SectionHead><div className="s-material-layout"><div><h2>THE FEEL<br/>OF THINGS.</h2><div className="s-material-tabs" role="tablist" aria-label="Explore materials">{materialItems.map(([name],i)=><button role="tab" id={`material-tab-${i}`} aria-controls="material-panel" aria-selected={index===i} tabIndex={index===i?0:-1} key={name} onClick={()=>setIndex(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();const next=(index+(e.key==='ArrowRight'?1:2))%3;setIndex(next);document.getElementById(`material-tab-${next}`)?.focus()}}}><span>0{i+1}</span>{name}<ArrowUpRight size={18}/></button>)}</div></div><div id="material-panel" role="tabpanel" aria-labelledby={`material-tab-${index}`}><Media src={materialItems[index][3]} alt={materialItems[index][0]+' architectural detail'}/><h3>{materialItems[index][1]}</h3><p>{materialItems[index][2]}</p></div></div></section>}
export function DailyRhythm(){const [index,setIndex]=useState(0),moments=[['07:00','Start outside.','A little fresh air before the rest of the day.','/story/forest.webp'],['12:30','Find your pause.','An unhurried moment in the garden.','/story/courtyard.webp'],['18:00','Come together.','Familiar faces. A favourite place to meet.','/era/lounge.webp'],['21:00','Let the city fade.','Close the door. Make the evening your own.','/era/interior.webp']];return <section className="s-rhythm s-pad"><SectionHead number="05" aside="FROM FIRST LIGHT TO LAST">A DAY, YOUR WAY</SectionHead><div className="s-rhythm-layout"><div><h2>SMALL<br/>MOMENTS.<br/>A FULL LIFE.</h2><div className="s-time-tabs">{moments.map(([time],i)=><button key={time} onClick={()=>setIndex(i)} aria-pressed={index===i}>{time}<span>{i===index?'—':'+'}</span></button>)}</div></div><div className="s-rhythm-picture"><Media src={moments[index][3]} alt={moments[index][1]}/><div aria-live="polite"><h3>{moments[index][1]}</h3><p>{moments[index][2]}</p></div></div></div></section>}
