export const articles=[
 {slug:'the-space-between',category:'Landscape',title:'The space between.',image:'/story/forest.webp',standfirst:'A building is only half the story. The spaces around it shape how a place feels, and how we feel within it.',body:[['A different starting point','Imagine arriving home through a garden. The pace changes before the front door. A turn in the path brings a tree into view; a sheltered seat invites a pause. At AFRAH, this is the starting point for the landscape story.'],['Room for the unplanned','Not every outdoor space needs a fixed purpose. A clearing can become a meeting place, a quiet place to read, or a small discovery on a familiar walk. A generous landscape leaves room for people to make it their own.'],['The longer view','Nature brings another measure of time to architecture. Moving shadows, seasonal colour and the growth of planting give a place new character long after the first arrival. The design ambition is a home that continues to unfold.']]},
 {slug:'a-study-in-light',category:'Architecture',title:'A study in light.',image:'/era/portrait.webp',standfirst:'The same facade can tell a different story from morning to evening. Light makes architecture a living experience.',body:[['Depth before decoration','Recessed windows, projecting edges and a stepped silhouette create a rhythm of light and shade. The visual interest comes from the building itself: its depth, its proportion and the way it meets the sky.'],['The quieter details','A handrail catches the afternoon sun. A pale wall carries a soft reflection. These small encounters are part of the architectural experience, alongside the distant view of a skyline.'],['After the sun goes down','Evening changes the scale of a building. The large silhouette gives way to the warmth of individual rooms and the welcome of an entrance. Our study explores that transition, from a presence in the city to a place to come home.']]},
 {slug:'everyday-rituals',category:'Interiors',title:'Everyday, considered.',image:'/era/lounge.webp',standfirst:'A room earns its place in our lives through the ordinary things we do there. The best design makes those moments feel natural.',body:[['A place for the first coffee','Morning light, a comfortable chair, a surface within reach. A satisfying room often begins with a simple arrangement rather than a dramatic gesture. The interior story at AFRAH starts with daily rituals.'],['Materials at a human scale','A stone surface feels cool to the touch. Timber adds visual warmth. A metal edge catches the light. Looking closely at these transitions helps us understand how a room can feel both composed and inviting.'],['Room to change','A home is never finished in quite the same way as a drawing. Books arrive, favourite objects find their places, and routines change. Our vision leaves space for the personal details that make a residence yours.']]}
];
export const residenceData=[
 {id:'08.A',floor:8,collection:'Courtyard',area:112,aspect:'East',image:'/story/courtyard.webp'},
 {id:'12.B',floor:12,collection:'Terrace',area:128,aspect:'South',image:'/media/living.webp'},
 {id:'16.C',floor:16,collection:'Skyline',area:136,aspect:'West',image:'/era/hero.webp'},
 {id:'18.A',floor:18,collection:'Terrace',area:142,aspect:'East',image:'/era/interior.webp'},
 {id:'22.B',floor:22,collection:'Skyline',area:154,aspect:'South',image:'/era/finale.webp'},
 {id:'26.D',floor:26,collection:'Skyline',area:168,aspect:'West',image:'/story/silver-hero.webp'}
];
