from pathlib import Path
p=Path('src/scene/Landscape.jsx')
s=p.read_text().replace('new THREE.IcosahedronGeometry(1,1)','new THREE.IcosahedronGeometry(1,0)')
s=s.replace('j<28','j<140').replace('i*40+j','i*150+j').replace('s:[.9+rand(j),1+rand(j+4)*1.5,.9+rand(j+7)]','s:[.3+rand(j)*.65,.35+rand(j+4)*.7,.3+rand(j+7)*.65]')
s=s.replace('leaf:new THREE.MeshStandardMaterial({roughness:1})',"leaf:new THREE.MeshStandardMaterial({color:'#52623a',roughness:1})")
p.write_text(s)
p=Path('src/scene/World.jsx');s=p.read_text().replace("gl.toneMappingExposure=1;",'gl.toneMappingExposure=1;')
s=s.replace('const a=progress.current.atmosphere;', 'const a=progress.current.atmosphere;gl.toneMappingExposure=1-a*.25;')
s=s.replace('sun.current.intensity=2.3-a*2.2','sun.current.intensity=2.3-a*2.27').replace('ambient.current.intensity=.7-a*.49','ambient.current.intensity=.7-a*.59').replace('fill.current.intensity=.4-a*.12','fill.current.intensity=.4-a*.29')
s=s.replace('scene.environmentIntensity=1-a*.66','scene.environmentIntensity=1-a*.9')
s=s.replace("pos=mobile?[82,55,103]:[82,47,99];look=mobile?[0,22,0]:[14,20,0]", "pos=mobile?[114,64,154]:[110,53,133];look=mobile?[0,30,0]:[3,30,0]")
s=s.replace('export default function World({state,onReady,selected,onSelect})','export default function World({state,onReady,selected,onSelect,active=true})').replace('<Canvas shadows dpr={[1,1.5]}','<Canvas frameloop={active?\'always\':\'never\'} shadows dpr={[1,1.5]}')
p.write_text(s)
p=Path('src/App.jsx');s=p.read_text().replace('<World state={state}', '<World active={canvasVisible&&!menu&&!film&&!plan&&!enquiry&&!privacy} state={state}')
s=s.replace('alt="A quiet bedroom with rich natural textures"','alt="Natural stone and crafted interior details"').replace('/media/bedroom.webp','/media/detail.webp').replace('02 — PRIVATE COMFORT','02 — CRAFTED DETAILS')
s=s.replace("useEffect(()=>{document.body.style.overflow=menu?'hidden':'';return()=>{document.body.style.overflow=''}},[menu]);", """useEffect(()=>{if(!menu)return;const previous=document.activeElement;document.body.style.overflow='hidden';const targets=()=>[...document.querySelectorAll('.menu-button,.menu-panel a,.menu-panel button')];targets()[1]?.focus();const trap=e=>{if(e.key!=='Tab')return;const list=targets(),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow='';document.removeEventListener('keydown',trap);previous?.focus()};},[menu]);""")
p.write_text(s)
