import {useCallback,useEffect,useRef,useState,lazy,Suspense} from 'react';
import {ArrowUpRight,ArrowDown,ArrowRight,X,Plus,Minus,Play,Volume2,VolumeX,Check,ChevronLeft,ChevronRight} from 'lucide-react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
const World=lazy(()=>import('./scene/World'));
const sections=[['architecture','Architecture'],['interiors','Interiors'],['residences','Residences'],['place','The gardens']];

function FloorPlan({unit}){
 return <svg className="floor-plan" viewBox="0 0 560 420" role="img" aria-label={`Illustrative two-bedroom layout, residence ${unit}`}><g fill="none" stroke="currentColor"><path strokeWidth="6" d="M45 40H510V360H45Z M45 218H270V360 M270 40V145 M270 190V218H510 M380 218V360 M155 218V290"/><path strokeWidth="1" d="M45 385H510M45 377V393M510 377V393 M80 40V28H240V40 M300 40V28H465V40 M45 360V347H230V360 M400 360V347H485V360"/><path strokeWidth="2" d="M65 80H115V175H65Z M122 88H205V165H122Z M330 75H460V158H330Z M355 235H285V325H355Z M397 235H491V325H397Z M65 238H138V283H65Z M181 238H240V277H181Z"/><circle cx="228" cy="132" r="23"/><path strokeWidth="1" d="M270 145Q315 145 315 190H270 M155 290Q190 290 190 325H155"/></g><g fill="currentColor" fontFamily="Inter,Arial" fontSize="10" letterSpacing="1"><text x="90" y="198">LIVING</text><text x="355" y="187">DINING</text><text x="287" y="345">BEDROOM 01</text><text x="402" y="345">BEDROOM 02</text><text x="65" y="312">BATH</text><text x="203" y="312">HALL</text><text x="218" y="409">PRIVATE TERRACE</text></g></svg>;
}

function Dialog({children,title,onClose,className=''}){
 const ref=useRef(),previous=useRef(document.activeElement);
 useEffect(()=>{const el=ref.current;el.showModal();return()=>{el.close();previous.current?.focus?.()};},[]);
 return <dialog ref={ref} className={`dialog ${className}`} aria-label={title} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><button className="dialog-close icon-button" onClick={onClose} aria-label="Close"><X size={23}/></button>{children}</dialog>;
}

function Enquiry({residence,onClose}){
 const [status,setStatus]=useState('idle'),[reference,setReference]=useState(''),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setStatus('sending');setError('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const res=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,residence})});const data=await res.json();if(!res.ok)throw Error(data.error||'Please try again.');setReference(data.reference);setStatus('sent');}catch(e){setError('We couldn’t save your enquiry. Please try again.');setStatus('idle');}}
 return <Dialog title="Arrange a private viewing" onClose={onClose} className="enquiry-dialog">{status==='sent'?<div className="success"><Check size={35}/><span className="eyebrow">ENQUIRY RECEIVED</span><h2>Thank you.</h2><p>Your preferences have been saved.</p><p className="small">Your reference: {reference}</p><button className="text-link" onClick={onClose}>Return to Afrah <ArrowRight size={18}/></button></div>:<><span className="eyebrow">A PERSONAL INTRODUCTION</span><h2>Come in.</h2><p>Arrange a private viewing, or tell us what you’re looking for.</p><form onSubmit={submit}><label>Your name<input name="name" autoComplete="name" required maxLength={120} placeholder="Full name"/></label><label>Email address<input type="email" name="email" autoComplete="email" required maxLength={200} placeholder="you@example.com"/></label><label>Phone <span className="optional">optional</span><input type="tel" name="phone" autoComplete="tel" maxLength={50} placeholder="Country code and number"/></label><label>I'm interested in<select name="interest" defaultValue={residence?'residence':'viewing'}><option value="viewing">A private viewing</option><option value="residence">A residence</option><option value="information">Further information</option></select></label>{residence&&<p className="small">Residence {residence}</p>}<label className="consent"><input type="checkbox" name="consent" value="yes" required/><span>I agree to my details being used to respond to this enquiry.</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="submit-button" disabled={status==='sending'}>{status==='sending'?'Saving…':'Send enquiry'}<ArrowUpRight size={19}/></button><p className="form-note">Your details are kept private and used only for your enquiry.</p></form></>}</Dialog>;
}

export default function App(){
 const [ready,setReady]=useState(false),[menu,setMenu]=useState(false),[mode,setMode]=useState('auto'),[section,setSection]=useState('hero'),[floor,setFloor]=useState(8),[unit,setUnit]=useState('A'),[plan,setPlan]=useState(false),[enquiry,setEnquiry]=useState(false),[film,setFilm]=useState(false),[privacy,setPrivacy]=useState(false),[sound,setSound]=useState(false),[place,setPlace]=useState('garden');
 const root=useRef(),loader=useRef(),stage=useRef(),soundEngine=useRef(null),frame=useRef(0),currentSection=useRef('hero');
 const reduced=useRef(window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 const state=useRef({progress:0,mode:'auto',section:'hero',pointerX:0,reduced:reduced.current});
 const onReady=useCallback(()=>setReady(true),[]);
 const dusk=mode==='dusk'||(mode==='auto'&&['light','afterdark'].includes(section));
 const residence=`${String(floor).padStart(2,'0')}.${unit}`;

 useEffect(()=>{const timer=setTimeout(()=>setReady(true),7000);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(ready)gsap.to(loader.current,{autoAlpha:0,duration:reduced.current?.1:.8,delay:.15,ease:'power2.inOut'});},[ready]);
 useEffect(()=>{state.current.mode=mode;document.documentElement.dataset.atmosphere=dusk?'dusk':'day';},[mode,dusk]);
 useEffect(()=>{if(!menu)return;const previous=document.activeElement;document.body.style.overflow='hidden';const targets=()=>[...document.querySelectorAll('.menu-button,.menu-panel a,.menu-panel button')];targets()[1]?.focus();const trap=e=>{if(e.key!=='Tab')return;const list=targets(),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow='';document.removeEventListener('keydown',trap);previous?.focus()};},[menu]);
 useEffect(()=>{const onKey=e=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{
  const context=gsap.context(()=>{
   if(!reduced.current){gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:45,opacity:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%',once:true}}));gsap.utils.toArray('[data-parallax]').forEach(el=>gsap.fromTo(el,{yPercent:-5},{yPercent:5,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:true}}));}
  },root);
  const update=()=>{frame.current=0;const h=window.innerHeight,y=window.scrollY;state.current.progress=Math.min(1,y/(stage.current.offsetHeight-h));let active='hero';const regions=[['architecture','architecture-scene'],['light','light-scene'],['material','material'],['enter','enter'],['interiors','interiors'],['residences','residences'],['place','place'],['afterdark','afterdark'],['contact','contact']];for(const[key,id]of regions){const el=document.getElementById(id);if(el&&el.getBoundingClientRect().top<h*.5)active=key;}state.current.section=active;if(currentSection.current!==active){currentSection.current=active;setSection(active);}document.documentElement.style.setProperty('--scroll-progress',String(y/(document.documentElement.scrollHeight-h)));};
  const scroll=()=>{if(!frame.current)frame.current=requestAnimationFrame(update)};window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);const pointer=e=>{state.current.pointerX=(e.clientX/window.innerWidth-.5)*2};window.addEventListener('pointermove',pointer,{passive:true});update();
  const path=window.location.pathname.slice(1);if(['architecture','residences','interiors','contact'].includes(path))setTimeout(()=>document.getElementById(path==='architecture'?'architecture-scene':path)?.scrollIntoView(),250);
  return()=>{context.revert();cancelAnimationFrame(frame.current);window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);window.removeEventListener('pointermove',pointer)};
 },[]);

 async function toggleSound(){
  if(sound){soundEngine.current?.suspend();setSound(false);return;}
  try{if(!soundEngine.current){const ctx=new (window.AudioContext||window.webkitAudioContext)(),buffer=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+Math.random()*.04-.02)/1.015;data[i]=last;}const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;filter.type='lowpass';filter.frequency.value=420;gain.gain.value=.13;source.connect(filter);filter.connect(gain);gain.connect(ctx.destination);source.start();soundEngine.current=ctx;}await soundEngine.current.resume();setSound(true);}catch{setSound(false);}
 }
 useEffect(()=>{const hidden=()=>{if(document.hidden)soundEngine.current?.suspend();else if(sound)soundEngine.current?.resume()};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden)},[sound]);
 function navigate(){setMenu(false)}
 function selectFloor(i){if(i>0)setFloor(i)}
 const canvasVisible=!['material','interiors','contact'].includes(section);
 const lightUi=(dusk&&canvasVisible)||['interiors','contact'].includes(section);
 return <div ref={root} className={`app ${dusk?'is-dusk':''}`}>
  <a className="skip-link" href="#residences">Skip to residences</a>
  <div ref={loader} className="loader" aria-hidden={ready}><span className="loader-brand">AFRAH</span><div className="loader-line"><i/></div><span className="loader-caption">CONSIDERED RESIDENCES</span></div>
  <div className={`world ${canvasVisible?'':'world-obscured'} ${section==='residences'?'world-interactive':''}`} aria-label="Interactive Afrah architecture"><Suspense fallback={null}><World active={canvasVisible&&!menu&&!film&&!plan&&!enquiry&&!privacy} state={state} onReady={onReady} selected={section==='residences'?floor:null} onSelect={selectFloor}/></Suspense></div>
  <header className={`site-header ${menu?'menu-active':''} ${section==='enter'?'header-solid':''} ${lightUi?'header-light':''}`}><a href="#" className="wordmark" aria-label="Afrah home">AFRAH</a><nav aria-label="Main navigation"><a href="#architecture-scene">Architecture</a><a href="#residences">Residences</a></nav><div className="header-end"><button className="viewing-link" onClick={()=>setEnquiry(true)}>Private viewing <ArrowUpRight size={14}/></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu}>{menu?<X size={23}/>:<><span/><span/></>}</button></div></header>
  {menu&&<div className="menu-panel" role="dialog" aria-modal="true" aria-label="Navigation"><div className="menu-image"><img src="/media/living.webp" alt="A light-filled living room"/></div><div className="menu-links">{sections.map(([id,title],i)=><a key={id} href={`#${id==='architecture'?'architecture-scene':id}`} onClick={navigate}><sup>0{i+1}</sup>{title}<ArrowUpRight/></a>)}<button className="text-link" onClick={()=>{setMenu(false);setEnquiry(true)}}>Arrange a private viewing <ArrowUpRight size={20}/></button></div><span className="menu-footer">SPACE. LIGHT. AFRAH.</span></div>}
  <main>
   <div ref={stage} className="cinema-stage" id="home">
    <section className="hero cinema-scene"><div className="hero-copy"><span className="eyebrow hero-label">A NEW PERSPECTIVE ON HOME</span><h1>Room to<br/>breathe.</h1><p>Considered residences.<br/>A quieter way of living.</p><a className="text-link" href="#residences">Discover the residences <ArrowUpRight size={18}/></a></div><div className="hero-foot"><a href="#architecture-scene" className="scroll-cue"><span className="circle-arrow"><ArrowDown size={17}/></span>SCROLL TO DISCOVER</a><span className="hero-location">ARCHITECTURE IN BALANCE</span><span className="hero-index">01 — 04</span></div><span className="hero-vertical">FORMED AROUND YOU</span></section>
    <section className="architecture-scene cinema-scene" id="architecture-scene"><div className="scene-copy reveal"><span className="eyebrow">01 / THE ARCHITECTURE</span><h2>In balance.</h2><p>Quiet stone. Deep terraces.<br/>An open relationship with the sky.</p></div><span className="architectural-caption">A DISTINCTIVE SILHOUETTE.<br/>A HUMAN SCALE.</span></section>
    <section className="light-scene cinema-scene" id="light-scene"><div className="light-copy reveal"><span className="eyebrow">02 / LIGHT & SPACE</span><h2>Follow<br/>the light.</h2><span className="time-display">{dusk?'19:21':'08:42'}</span><p>Different light. The same place.</p></div></section>
   </div>
   <section className="material-section surface" id="material"><div className="editorial-heading reveal"><span className="eyebrow">03 / THE FINER DETAILS</span><h2>Nothing excessive.<br/>Everything considered.</h2></div><div className="material-layout"><figure className="material-main image-reveal"><img src="/media/living.webp" data-parallax alt="Daylight falling across warm stone and natural interiors" loading="lazy"/><figcaption><span>01 — NATURAL MATERIALS</span><span>TACTILE. TIMELESS.</span></figcaption></figure><div className="material-aside"><p className="editorial-body reveal">The warmth of stone.<br/>The precision of metal.<br/>The softness of natural light.</p><figure className="image-reveal"><img src="/media/interior-still.webp" data-parallax alt="Natural stone and crafted interior details" loading="lazy"/><figcaption>02 — PRIVATE COMFORT</figcaption></figure><a className="text-link" href="#interiors">A closer look <ArrowUpRight size={19}/></a></div></div><div className="material-words" aria-hidden="true">STONE <span>—</span> GLASS <span>—</span> LIGHT</div></section>
   <section id="enter" className="enter-scene cinema-scene"><div className="enter-copy reveal"><span className="eyebrow">BEYOND THE FACADE</span><h2>Come inside.</h2><a className="circle-arrow" href="#interiors" aria-label="Discover the interiors"><ArrowDown/></a></div></section>
   <section id="interiors" className="interior-section"><div className="interior-image"><img src="/media/living.webp" data-parallax alt="A spacious residence, arranged for quiet everyday living" loading="lazy"/><div className="image-shade"/></div><div className="interior-content"><span className="eyebrow">04 / LIFE AT AFRAH</span><h2>Life.<br/>Unhurried.</h2><button className="film-button" onClick={()=>setFilm(true)}><span className="circle-arrow"><Play size={16} fill="currentColor"/></span>WATCH THE FILM <span className="film-length">00:18</span></button></div><span className="interior-caption">ROOM FOR THE EVERYDAY.</span></section>
   <section id="residences" className="residences-section cinema-scene"><div className="residence-intro"><span className="eyebrow">05 / FIND YOUR HOME</span><h2>A place<br/>of your own.</h2><p>Choose a level.<br/>Discover your perspective.</p></div><div className="residence-selector"><div className="floor-control"><button className="icon-button" aria-label="Lower floor" onClick={()=>setFloor(Math.max(1,floor-1))} disabled={floor===1}><Minus size={18}/></button><div><span className="eyebrow">LEVEL</span><strong>{String(floor).padStart(2,'0')}</strong></div><button className="icon-button" aria-label="Higher floor" onClick={()=>setFloor(Math.min(11,floor+1))} disabled={floor===11}><Plus size={18}/></button></div><div className="floor-track" aria-label="Choose a floor">{Array.from({length:11},(_,i)=>i+1).map(i=><button key={i} aria-label={`Level ${i}`} aria-pressed={floor===i} onClick={()=>setFloor(i)}><span>{i}</span></button>)}</div><div className="residence-row"><span className="eyebrow">RESIDENCE</span><div className="unit-buttons">{['A','B','C','D'].map(u=><button key={u} onClick={()=>setUnit(u)} aria-pressed={unit===u}>{u}</button>)}</div></div><div className="residence-description"><span>Residence {residence}</span><span>{floor>8?'Terrace collection':'Garden collection'}</span></div><button className="text-link" onClick={()=>setPlan(true)}>View residence <ArrowUpRight size={19}/></button><span className="selector-note">Select a level on the building or use the controls.</span></div></section>
   <section id="place" className="place-section cinema-scene"><div className="place-copy"><span className="eyebrow">06 / A LITTLE CLOSER TO NATURE</span><h2>Open air.<br/>Every day.</h2><p>{place==='garden'?'A green edge. A quiet walk. Space to pause.':place==='terraces'?'An outdoor room, above the everyday.':'A considered welcome, from the first step.'}</p><div className="place-tabs">{[['garden','The gardens'],['terraces','The terraces'],['arrival','The arrival']].map(([id,name])=><button key={id} aria-pressed={place===id} onClick={()=>setPlace(id)}>{name}</button>)}</div></div><div className={`place-point point-${place}`}><span/><p>{place==='garden'?'THE GARDENS':place==='terraces'?'PRIVATE TERRACES':'THE ARRIVAL'}</p></div></section>
   <section id="afterdark" className="afterdark-section cinema-scene"><span className="eyebrow">07 / ANOTHER SIDE OF HOME</span><h2>After dark.</h2><span className="afterdark-wordmark" aria-hidden="true">AFRAH</span></section>
   <section id="contact" className="contact-section"><span className="eyebrow reveal">YOUR NEXT CHAPTER</span><h2 className="reveal">Make yourself<br/>at home.</h2><button className="contact-cta reveal" onClick={()=>setEnquiry(true)}>ARRANGE A PRIVATE VIEWING <ArrowUpRight size={28}/></button><a className="secondary-contact" href="#residences">Explore residences</a><footer><a href="#" className="wordmark">AFRAH</a><span>CONSIDERED RESIDENCES</span><div><button onClick={()=>setPrivacy(true)}>Privacy</button><span>© {new Date().getFullYear()} AFRAH</span></div></footer></section>
  </main>
  {!menu&&<div className={`experience-controls ${lightUi?'controls-light':''}`}><div className="day-dusk" role="group" aria-label="Architectural lighting"><button aria-pressed={!dusk} onClick={()=>setMode('day')}>DAY</button><span>/</span><button aria-pressed={dusk} onClick={()=>setMode('dusk')}>DUSK</button></div><button className="sound-toggle" aria-label={sound?'Turn sound off':'Turn sound on'} aria-pressed={sound} onClick={toggleSound}>{sound?<Volume2 size={15}/>:<VolumeX size={15}/>}<span>SOUND {sound?'ON':'OFF'}</span></button></div>}
  <div className="page-progress"/>
  {plan&&<Dialog title={`Residence ${residence}`} onClose={()=>setPlan(false)} className="plan-dialog"><div><span className="eyebrow">THE RESIDENCES / LEVEL {String(floor).padStart(2,'0')}</span><h2>Residence {residence}</h2><FloorPlan unit={residence}/></div><div className="plan-details"><span className="eyebrow">A PRIVATE PERSPECTIVE</span><h3>Space for<br/>your everyday.</h3><dl><div><dt>Collection</dt><dd>{floor>8?'Terrace':'Garden'}</dd></div><div><dt>Aspect</dt><dd>{unit==='A'||unit==='B'?'South':'North'}</dd></div><div><dt>Layout</dt><dd>Two bedrooms</dd></div><div><dt>Outdoor space</dt><dd>Private terrace</dd></div></dl><button className="text-link" onClick={()=>{setPlan(false);setEnquiry(true)}}>Enquire about this residence <ArrowUpRight size={18}/></button><p className="fineprint">Illustrative layout. Specification and availability are confirmed on enquiry.</p></div></Dialog>}
  {enquiry&&<Enquiry residence={section==='residences'?residence:null} onClose={()=>setEnquiry(false)}/>}
  {film&&<Dialog title="Life at Afrah — film" onClose={()=>setFilm(false)} className="film-dialog"><video controls autoPlay playsInline poster="/media/living.webp"><source src="/media/afrah-life.mp4" type="video/mp4"/></video><span className="eyebrow">AFRAH — LIFE, UNHURRIED.</span></Dialog>}
  {privacy&&<Dialog title="Privacy" onClose={()=>setPrivacy(false)} className="privacy-dialog"><span className="eyebrow">YOUR PRIVACY</span><h2>In confidence.</h2><p>The enquiry form collects the contact details and preferences you choose to provide. They are stored by this website to manage your request. No advertising trackers are used.</p><p>Contact details are not published or sent to a third-party marketing service. You may choose not to submit the form.</p></Dialog>}
 </div>;
}

