import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,ArrowRight,ChevronLeft,ChevronRight,Heart,Menu,X,Plus,Minus,Play,Volume2,VolumeX,RotateCcw} from 'lucide-react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import {Dialog,Enquiry,FloorPlan} from './Forms';
import FormChapter from './FormChapter';
gsap.registerPlugin(ScrollTrigger);
const EraCity=lazy(()=>import('./scene/EraCity'));
const gallery=[['lobby','A considered welcome'],['lounge','Room to unwind'],['gallery','The finer details'],['hall','Everyday rituals'],['interior','A quieter pace']];
const nav=[['about','About Afrah'],['architecture','Architecture'],['form','Form & feeling'],['gardens','The gardens'],['interiors','Interiors'],['residences','Residences']];

function Branches({className=''}){return <svg className={`branches ${className}`} viewBox="0 0 1400 1500" fill="none" aria-hidden="true"><path d="M700 1500V0M700 300C660 170 600 140 560 95M700 300C740 170 800 140 840 95M700 600C530 260 220 190 50 80M700 600C870 260 1180 190 1350 80M700 900C615 735 490 640 340 580M700 900C785 735 910 640 1060 580M700 1260C520 990 310 1030 90 840M700 1260C880 990 1090 1030 1310 840"/></svg>}
function Intro({onDone}){
 const ref=useRef(),ended=useRef(false),[progress,setProgress]=useState(0),timer=useRef();
 const finish=useCallback(()=>{if(ended.current)return;ended.current=true;clearTimeout(timer.current);setProgress(100);gsap.to(ref.current,{clipPath:'inset(0 0 100% 0)',duration:1.25,ease:'power3.inOut',onComplete:onDone});},[onDone]);
 const ready=useCallback(()=>{setProgress(100);timer.current=setTimeout(finish,4000)},[finish]);
 useEffect(()=>{document.body.style.overflow='hidden';const limit=setTimeout(finish,8500);return()=>{clearTimeout(limit);clearTimeout(timer.current);document.body.style.overflow=''}},[finish]);
 return <div ref={ref} className="era-intro"><Branches/><Suspense fallback={null}><EraCity intro onReady={ready} onProgress={n=>setProgress(Math.round(n*90))}/></Suspense><div className="intro-top"><span>AFRAH</span><span>AN EXTRAORDINARY EVERYDAY</span></div><div className="intro-title">AFRAH</div><div className="intro-bottom"><span>ENTER A NEW PERSPECTIVE</span><span className="intro-progress">{String(progress).padStart(3,'0')} / 100</span><button className="pill" onClick={finish}>SKIP INTRO <ArrowRight size={14}/></button></div></div>
}

function ResidenceExplorer({saved,onSave,onEnquire}){
 const [level,setLevel]=useState(18),[unit,setUnit]=useState('A'),[plan,setPlan]=useState(false);const id=`${String(level).padStart(2,'0')}.${unit}`;
 return <><div className="residence-tools"><span className="micro">FIND YOUR PERSPECTIVE</span><div className="level-picker"><button aria-label="Lower floor" disabled={level===1} onClick={()=>setLevel(Math.max(1,level-1))}><Minus/></button><div><span>LEVEL</span><strong>{String(level).padStart(2,'0')}</strong></div><button aria-label="Higher floor" disabled={level===30} onClick={()=>setLevel(Math.min(30,level+1))}><Plus/></button></div><div className="unit-picker"><span>RESIDENCE</span>{['A','B','C','D'].map(u=><button key={u} onClick={()=>setUnit(u)} aria-pressed={unit===u}>{u}</button>)}</div><div className="residence-summary"><p>Residence {id}</p><button aria-label={saved.includes(id)?'Remove saved residence':'Save residence'} aria-pressed={saved.includes(id)} onClick={()=>onSave(id)}><Heart fill={saved.includes(id)?'currentColor':'none'} size={19}/></button></div><button className="pill peach wide" onClick={()=>setPlan(true)}>EXPLORE RESIDENCE <ArrowUpRight size={16}/></button><span className="residence-footnote">YOUR OWN VIEW OF THE CITY</span></div>{plan&&<Dialog title={`Residence ${id}`} className="plan-dialog" onClose={()=>setPlan(false)}><div><span className="micro">AFRAH / LEVEL {level}</span><h2>Residence {id}</h2><FloorPlan unit={id}/></div><div className="plan-details"><span className="micro">A PRIVATE PERSPECTIVE</span><h3>Make room<br/>for living.</h3><dl><div><dt>Layout</dt><dd>Two bedrooms</dd></div><div><dt>Outdoor space</dt><dd>Private terrace</dd></div><div><dt>Aspect</dt><dd>{['A','B'].includes(unit)?'South':'North'}</dd></div></dl><button className="pill peach wide" onClick={()=>{setPlan(false);onEnquire(id)}}>ENQUIRE <ArrowUpRight size={16}/></button><p className="fineprint">Illustrative layout and residence selection. Final specifications and availability are confirmed on enquiry.</p></div></Dialog>}</>
}

export default function EraApp(){
 const root=useRef(),lenis=useRef(),audioEngine=useRef(),[intro,setIntro]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[menu,setMenu]=useState(false),[hideDock,setHideDock]=useState(false),[enquiry,setEnquiry]=useState(null),[film,setFilm]=useState(false),[map,setMap]=useState(false),[privacy,setPrivacy]=useState(false),[shortlist,setShortlist]=useState(false),[sound,setSound]=useState(false),[slide,setSlide]=useState(0),[rotation,setRotation]=useState(0),[zoom,setZoom]=useState(1),[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem('afrah-saved')||'[]')}catch{return[]}});
 const done=useCallback(()=>setIntro(false),[]);const overlay=intro||menu||enquiry!==null||film||map||privacy||shortlist;
 useEffect(()=>{if(overlay)lenis.current?.stop();else lenis.current?.start()},[overlay]);
 useEffect(()=>{
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(!reduced){const smooth=new Lenis({lerp:.085,smoothWheel:true,wheelMultiplier:.8,anchors:true});lenis.current=smooth;smooth.on('scroll',ScrollTrigger.update);gsap.ticker.lagSmoothing(0);const tick=time=>smooth.raf(time*1000);gsap.ticker.add(tick);smooth._tick=tick;if(intro)smooth.stop();}
  const mm=gsap.matchMedia();const context=gsap.context(()=>{
   ScrollTrigger.create({trigger:'#residences',start:'top 70%',endTrigger:'.era-footer',end:'bottom bottom',onToggle:self=>setHideDock(self.isActive)});
   mm.add('(prefers-reduced-motion: no-preference)',()=>{
    gsap.timeline({scrollTrigger:{trigger:'.hero-track',start:'top top',end:'bottom bottom',scrub:1.15,invalidateOnRefresh:true}}).fromTo('.hero-picture',{width:()=>innerWidth<701?'86%':'76%',left:()=>innerWidth<701?'7%':'12%',top:()=>innerWidth<701?'43%':'54%',height:()=>innerWidth<701?'78%':'100%'},{width:'100%',left:'0%',top:'0%',height:'100%',borderRadius:0,ease:'none'},0).to('.hero-heading',{yPercent:-35,opacity:0,ease:'none'},0).to('.hero-tagline',{y:-120,opacity:0,ease:'none'},0).fromTo('.hero-image',{scale:1.08},{scale:1,ease:'none'},0).fromTo('.hero-image-caption',{opacity:0,y:20},{opacity:1,y:0},.65);
    gsap.timeline({scrollTrigger:{trigger:'.architecture-track',start:'top top',end:'bottom bottom',scrub:1.1}}).fromTo('.tower-layer',{yPercent:28,scale:.82},{yPercent:0,scale:1.1,duration:.7,ease:'none'},0).fromTo('.architecture-title',{xPercent:12},{xPercent:-15,duration:.75,ease:'none'},0).fromTo('.arch-portal',{clipPath:'circle(0% at 50% 100%)'},{clipPath:'circle(145% at 50% 100%)',duration:.55,ease:'power1.inOut'},.55).fromTo('.portal-copy',{y:50,opacity:0},{y:0,opacity:1,duration:.2},.82);
    gsap.fromTo('.garden-image',{clipPath:'polygon(0 20%,33% 20%,33% 10%,66% 10%,66% 0,100% 0,100% 100%,0 100%)',scale:1.08},{clipPath:'polygon(0 0,33% 0,33% 0,66% 0,66% 0,100% 0,100% 100%,0 100%)',scale:1,ease:'none',scrollTrigger:{trigger:'.garden-stage',start:'top 85%',end:'center center',scrub:1}});
    gsap.fromTo('.interior-arch',{clipPath:'ellipse(36% 48% at 50% 50%)'},{clipPath:'ellipse(85% 85% at 50% 50%)',ease:'none',scrollTrigger:{trigger:'.interior-intro',start:'top 70%',end:'bottom bottom',scrub:1}});
    gsap.fromTo('.sculpture',{rotate:-18,y:70},{rotate:18,y:-60,ease:'none',scrollTrigger:{trigger:'.material-section',start:'top bottom',end:'bottom top',scrub:1.4}});
    gsap.fromTo('.residence-buildings',{yPercent:24},{yPercent:0,ease:'none',scrollTrigger:{trigger:'.residences',start:'top bottom',end:'top 10%',scrub:1}});
    gsap.utils.toArray('.rise').forEach(el=>gsap.from(el,{y:65,opacity:0,duration:1.3,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 91%',once:true}}));
    gsap.utils.toArray('[data-drift]').forEach(el=>gsap.fromTo(el,{yPercent:-5},{yPercent:5,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:1}}));
   });
  },root);
  const path=location.pathname.slice(1);const target=path==='contact'?'contact':path==='architecture'?'architecture':['interiors','residences'].includes(path)?path:null;
  const route=setTimeout(()=>{ScrollTrigger.refresh();if(target){setIntro(false);document.getElementById(target)?.scrollIntoView({behavior:'instant'})}},300);
  const refresh=()=>ScrollTrigger.refresh();document.fonts.ready.then(refresh);window.addEventListener('load',refresh);
  return()=>{clearTimeout(route);window.removeEventListener('load',refresh);context.revert();mm.revert();if(lenis.current){gsap.ticker.remove(lenis.current._tick);lenis.current.destroy();lenis.current=null}audioEngine.current?.close()};
 },[]);
 function go(id){setMenu(false);requestAnimationFrame(()=>{lenis.current?.start();if(lenis.current)lenis.current.scrollTo('#'+id,{duration:1.8});else document.getElementById(id)?.scrollIntoView({behavior:'smooth'})})}
 function toggleSave(id){setSaved(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem('afrah-saved',JSON.stringify(next));return next})}
 async function toggleSound(){try{if(sound){await audioEngine.current?.suspend();setSound(false);return}if(!audioEngine.current){const c=new AudioContext(),buffer=c.createBuffer(1,c.sampleRate*4,c.sampleRate),data=buffer.getChannelData(0);let x=0;for(let i=0;i<data.length;i++){x=(x+(Math.random()-.5)*.03)/1.015;data[i]=x}const source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=buffer;source.loop=true;filter.frequency.value=350;gain.gain.value=.1;source.connect(filter);filter.connect(gain);gain.connect(c.destination);source.start();audioEngine.current=c}await audioEngine.current.resume();setSound(true)}catch{setSound(false)}}
 useEffect(()=>{const change=()=>{if(document.hidden)audioEngine.current?.suspend();else if(sound)audioEngine.current?.resume()};document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change)},[sound]);
 return <div ref={root} className="era-app">
  <a href="#residences" className="skip-link">Skip to residences</a>
  {intro&&<Intro onDone={done}/>}
  <header className="era-header"><div className="header-left"><button className="pill peach" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu size={17}/><span>MENU</span></button><button className="pill header-select" onClick={()=>go('residences')}>SELECT RESIDENCE</button><button className="pill header-tour" onClick={()=>setFilm(true)}>VIRTUAL TOUR</button></div><a className="brand" href="#home" onClick={e=>{e.preventDefault();go('home')}}>AFRAH</a><div className="header-right"><button className="round outline shortlist-toggle" aria-label={`Saved residences, ${saved.length}`} onClick={()=>setShortlist(true)}><Heart size={17}/>{saved.length>0&&<sup>{saved.length}</sup>}</button><button className="pill peach request-call" onClick={()=>setEnquiry('')}>REQUEST A CALL</button><button className="round peach" aria-label={sound?'Turn sound off':'Turn sound on'} aria-pressed={sound} onClick={toggleSound}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button></div></header>
  <main>
   <section id="home" className="hero-track"><div className="hero-pin"><Branches/><h1 className="hero-heading"><span>PLACE</span><span>TO <em>LIVE</em></span></h1><p className="hero-tagline">THE ART OF COMING HOME</p><div className="hero-picture"><img className="hero-image" src="/era/hero.webp" alt="Art Deco towers in a sunset cityscape" fetchPriority="high"/><div className="hero-image-caption"><span>AFRAH RESIDENCES</span><span>A NEW PERSPECTIVE</span></div></div><button className="hero-scroll round peach" aria-label="Discover Afrah" onClick={()=>go('about')}><ArrowDown size={17}/></button></div></section>
   <section id="about" className="about-section section-pad"><Branches/><div className="section-top micro"><span>01 / THE VISION</span><span>AN EXTRAORDINARY EVERYDAY</span></div><h2 className="display about-title rise">A NEW<br/><span>WAY</span><br/>TO LIVE</h2><figure className="about-image"><img src="/era/portrait.webp" data-drift alt="A stepped residential tower viewed from the street" loading="lazy"/><figcaption>TIMELESS FROM EVERY ANGLE.</figcaption></figure><p className="about-statement rise">A DISTINCTIVE SILHOUETTE.<br/>A MORE CONSIDERED HOME.<br/><span>WELCOME TO AFRAH.</span></p><button className="round-link" onClick={()=>go('architecture')}><span>DISCOVER THE<br/>ARCHITECTURE</span><ArrowDown size={20}/></button></section>
   <section id="architecture" className="architecture-track"><div className="architecture-pin"><img className="architecture-sky" src="/era/sky.webp" alt="" loading="lazy"/><div className="architecture-kicker micro">02 / A DIFFERENT PERSPECTIVE</div><h2 className="architecture-title display">ARCHITECTURE</h2><img className="tower-layer" src="/era/tower.webp" alt="The sculpted crown and warm metallic facade of the tower" loading="lazy"/><div className="architecture-bottom"><span>SCULPTED BY LIGHT.</span><span>SHAPED FOR LIFE.</span></div><div className="arch-portal"><img src="/era/arch.webp" alt="A grand arched residential entrance"/><div className="portal-copy"><span className="micro">A PERSONAL WELCOME</span><h3>COME<br/>INSIDE.</h3><button className="pill peach" onClick={()=>go('interiors')}>EXPLORE INTERIORS <ArrowUpRight size={15}/></button></div></div></div></section>
   <FormChapter onExplore={()=>go('materials')}/>
   <section id="gardens" className="gardens section-pad"><Branches/><div className="section-top micro"><span>03 / EVERYDAY, ELEVATED</span><span>A LITTLE CLOSER TO NATURE</span></div><h2 className="display garden-title rise">ROOM<br/><span>TO</span> <em>BREATHE</em></h2><div className="garden-stage"><img className="garden-image" src="/era/garden.webp" alt="Landscaped courtyard gardens between the residences" loading="lazy"/><button className="round-link peach" onClick={()=>setMap(true)}>EXPLORE<br/>THE PLACE <ArrowUpRight size={20}/></button></div><div className="garden-copy"><span className="micro">A WORLD OF YOUR OWN</span><p className="rise">Open air. Quiet corners.<br/>A green retreat in the city.</p></div></section>
   <section id="materials" className="material-section section-pad"><span className="micro">04 / THE FINER DETAILS</span><div className="material-title"><h2 className="display rise">TOUCH.<br/>FEEL.<br/><em>BELONG.</em></h2><img className="sculpture" src="/era/sculpture.webp" alt="A sculptural arrangement of marble and bronze" loading="lazy"/></div><div className="material-editorial"><figure><img src="/media/living.webp" data-drift alt="Natural textures and warm light in a residence" loading="lazy"/><figcaption>THE WARMTH OF HOME.</figcaption></figure><div><p className="rise">STONE. METAL. LIGHT.<br/>DETAILS YOU FEEL,<br/>EVERY SINGLE DAY.</p><button className="pill outline-dark" onClick={()=>setFilm(true)}><Play size={13}/> WATCH THE FILM</button></div></div></section>
   <section id="interiors" className="interiors"><div className="interior-intro section-pad"><span className="micro">05 / LIFE ON THE INSIDE</span><h2 className="display rise">INNER<br/><span>WORLD</span></h2><div className="interior-arch"><img src="/era/ceiling.webp" alt="Sunlit double-height lounge with sculptural lighting" loading="lazy"/></div></div><div className="interior-gallery section-pad"><div className="gallery-heading"><p>THE ART OF<br/>FEELING AT HOME.</p><div className="gallery-controls"><span>{String(slide+1).padStart(2,'0')} / 05</span><button className="round outline-dark" aria-label="Previous interior" onClick={()=>setSlide((slide+4)%5)}><ChevronLeft size={20}/></button><button className="round outline-dark" aria-label="Next interior" onClick={()=>setSlide((slide+1)%5)}><ChevronRight size={20}/></button></div></div><div className="gallery-window"><div className="gallery-track" style={{transform:`translateX(calc(${slide} * -1 * (var(--gallery-width) + var(--gallery-gap))))`}}>{gallery.map(([img,title],i)=><figure key={img} aria-hidden={i!==slide}><img src={`/era/${img}.webp`} alt={title} loading="lazy"/><figcaption><span>0{i+1}</span><span>{title.toUpperCase()}</span></figcaption></figure>)}</div></div></div></section>
   <section id="residences" className="residences section-pad"><Branches/><span className="micro">06 / FIND YOUR HOME</span><h2 className="display rise">YOUR<br/><em>PERSPECTIVE</em></h2><div className="residence-stage"><img className="residence-buildings" src="/era/residenceTowers.webp" alt="A collection of illuminated residential towers" loading="lazy"/><ResidenceExplorer saved={saved} onSave={toggleSave} onEnquire={setEnquiry}/></div></section>
   <section id="contact" className="finale"><img className="finale-image" src="/era/finale.webp" alt="The residences at blue hour" loading="lazy"/><div className="finale-copy"><span className="micro rise">A NEW CHAPTER BEGINS</span><h2 className="display rise">MAKE IT<br/><em>YOURS.</em></h2><button className="round-link peach" onClick={()=>setEnquiry('')}>ARRANGE A<br/>PRIVATE VIEWING <ArrowUpRight size={23}/></button></div><div className="finale-brand">AFRAH</div></section>
   <footer className="era-footer section-pad"><div><a className="brand" href="#home" onClick={e=>{e.preventDefault();go('home')}}>AFRAH</a><span className="micro">THE ART OF COMING HOME</span></div><div className="footer-links"><button onClick={()=>setIntro(true)}>REPLAY INTRO <RotateCcw size={12}/></button><button onClick={()=>setPrivacy(true)}>PRIVACY</button><span>© {new Date().getFullYear()} AFRAH</span></div></footer>
  </main>
  {!overlay&&!hideDock&&<button className="map-dock peach" onClick={()=>setMap(true)}><span className="map-icon">3D</span><span>EXPLORE AFRAH</span><img src="/era/residenceTowers.webp" alt=""/></button>}
  {menu&&<Dialog title="Navigation" className="navigation-dialog" onClose={()=>setMenu(false)}><div className="menu-art"><img src="/era/portrait.webp" alt="The residences"/></div><nav>{nav.map(([id,name],i)=><button key={id} onClick={()=>go(id)}><sup>0{i+1}</sup>{name}<ArrowUpRight/></button>)}<button className="pill peach" onClick={()=>{setMenu(false);setEnquiry('')}}>ARRANGE A PRIVATE VIEWING</button></nav></Dialog>}
  {enquiry!==null&&<Enquiry residence={enquiry||null} onClose={()=>setEnquiry(null)}/>}
  {film&&<Dialog title="Life at Afrah — film" className="film-dialog" onClose={()=>setFilm(false)}><video controls autoPlay playsInline preload="metadata" poster="/media/living.webp"><source src="/media/afrah-life.mp4" type="video/mp4"/></video><span className="micro">AFRAH / LIFE, UNHURRIED.</span></Dialog>}
  {map&&<Dialog title="Explore Afrah in 3D" className="map-dialog" onClose={()=>setMap(false)}><span className="micro">A DIFFERENT PERSPECTIVE</span><h2>EXPLORE AFRAH</h2><Suspense fallback={<img className="map-fallback" src="/era/residenceTowers.webp" alt="The residences"/>}><EraCity rotation={rotation} zoom={zoom}/></Suspense><div className="map-tools"><button className="round outline" aria-label="Rotate left" onClick={()=>setRotation(rotation-.25)}><ChevronLeft/></button><button className="round outline" aria-label="Rotate right" onClick={()=>setRotation(rotation+.25)}><ChevronRight/></button><button className="round outline" aria-label="Zoom out" disabled={zoom<=.6} onClick={()=>setZoom(Math.max(.6,zoom-.2))}><Minus/></button><button className="round outline" aria-label="Zoom in" disabled={zoom>=1.8} onClick={()=>setZoom(Math.min(1.8,zoom+.2))}><Plus/></button><button className="pill peach" onClick={()=>{setMap(false);go('residences')}}>FIND A RESIDENCE <ArrowUpRight size={15}/></button></div></Dialog>}
  {shortlist&&<Dialog title="Saved residences" className="saved-dialog" onClose={()=>setShortlist(false)}><span className="micro">YOUR SELECTION</span><h2>Saved residences</h2>{saved.length?saved.map(id=><div className="saved-row" key={id}><span>Residence {id}</span><button className="pill outline-dark" onClick={()=>{setShortlist(false);setEnquiry(id)}}>ENQUIRE <ArrowUpRight size={14}/></button><button aria-label={`Remove ${id}`} onClick={()=>toggleSave(id)}><X size={17}/></button></div>):<><p>Your favourite residences, all in one place.</p><button className="pill peach" onClick={()=>{setShortlist(false);go('residences')}}>EXPLORE RESIDENCES <ArrowRight size={15}/></button></>}</Dialog>}
  {privacy&&<Dialog title="Privacy" className="privacy-dialog" onClose={()=>setPrivacy(false)}><span className="micro">YOUR PRIVACY</span><h2>In confidence.</h2><p>Enquiries store only the contact details and preferences you provide. Saved residences are kept in your browser. No advertising trackers are used.</p><p>Your contact details are not published or sent to a third-party marketing service.</p></Dialog>}
 </div>
}
