import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
const Sculpture=lazy(()=>import('./scene/CompositeSculpture'));
export default function FormChapter({onExplore}){
 const section=useRef(),progress=useRef(0),[mount,setMount]=useState(false),[active,setActive]=useState(0);
 useEffect(()=>{const io=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setMount(true);io.disconnect()}},{rootMargin:'900px'});io.observe(section.current);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const tl=gsap.timeline({scrollTrigger:{trigger:section.current,start:'top top',end:'bottom bottom',scrub:1.2,onUpdate:s=>{progress.current=s.progress;setActive(s.progress>.53?1:0)}}});tl.to('.form-title-a',{yPercent:-22,opacity:0,duration:.25},.22).fromTo('.form-title-b',{yPercent:25,opacity:0},{yPercent:0,opacity:1,duration:.25},.5).to('.form-grid',{rotation:12,scale:1.2,duration:1},0);});return()=>{io.disconnect();mm.revert()}},[]);
 return <section id="form" ref={section} className="form-chapter"><div className="form-pin"><div className="form-grid" aria-hidden="true"/><img className="form-poster" src="/composites/materials.jpg" alt="" loading="lazy"/>{mount&&<Suspense fallback={null}><Sculpture progress={progress}/></Suspense>}<div className="form-top micro"><span>FORM & FEELING / A DESIGN STUDY</span><span>[ AFRAH ATELIER ]</span></div><div className="form-headline form-title-a" aria-hidden={active!==0}><span className="micro">[ 01 / THE SILHOUETTE ]</span><h2>SHAPED<br/>BY NATURE.<br/><em>MADE FOR<br/>LIVING.</em></h2></div><div className="form-headline form-title-b" aria-hidden={active!==1} inert={active!==1}><span className="micro">[ 02 / THE EXPERIENCE ]</span><h2>STRONG<br/>IN FORM.<br/><em>SOFT IN<br/>FEELING.</em></h2><button className="pill peach" onClick={onExplore}>DISCOVER THE DETAILS <ArrowUpRight size={14}/></button></div><div className="form-bottom"><span className="micro">A DIALOGUE BETWEEN<br/>SCULPTURE AND ARCHITECTURE.</span><div className="form-progress" aria-label={`Design chapter ${active+1} of 2`}><span className={active===0?'active':''}>01</span><i/><span className={active===1?'active':''}>02</span></div><ArrowDown size={18}/></div></div></section>
}
