import {lazy,Suspense,useCallback,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Menu,Heart,X,Plus,Minus,ChevronLeft,ChevronRight,Box} from 'lucide-react';
import gsap from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import Lenis from 'lenis';
import {Dialog,Enquiry} from './Forms';
import {StoryContext,Link,chapters} from './story/Context';
import {Label,Media,TextLink} from './story/Components';
import {Home,Vision,Architecture,Landscape,Interiors,Residences,Journal,Article,Contact,NotFound} from './story/Pages';
gsap.registerPlugin(ScrollTrigger);
const City=lazy(()=>import('./scene/EraCity'));
const titles={'/':'A different nature','/vision':'The vision','/architecture':'Architecture','/landscape':'Landscape','/interiors':'Interiors','/residences':'Residences','/journal':'Journal','/contact':'Let’s begin'};
function page(path){if(path.startsWith('/journal/'))return <Article slug={path.split('/')[2]}/>;const pages={'/':Home,'/vision':Vision,'/architecture':Architecture,'/landscape':Landscape,'/interiors':Interiors,'/residences':Residences,'/journal':Journal,'/contact':Contact};const Page=pages[path]||NotFound;return <Page/>}
function Intro({done}){const ref=useRef(),[ready,setReady]=useState(false);useEffect(()=>{let alive=true;document.fonts.ready.then(()=>{if(alive)setReady(true)});const timer=setTimeout(()=>{gsap.to(ref.current,{yPercent:-100,duration:.8,ease:'power3.inOut',onComplete:done})},1600);return()=>{alive=false;clearTimeout(timer)}},[done]);return <div className="s-loader" ref={ref}><Label>AFRAH / A DIFFERENT NATURE</Label><div><span>FORM.</span><span>NATURE.</span><span>HUMAN.</span></div><footer><Label>{ready?'READY TO EXPLORE':'PREPARING YOUR EXPERIENCE'}</Label><button onClick={done}>ENTER AFRAH <ArrowRight size={17}/></button></footer></div>}
export default function StoryApp(){
 const[path,setPath]=useState(location.pathname.replace(/\/$/,'')||'/'),[menu,setMenu]=useState(false),[film,setFilm]=useState(false),[map,setMap]=useState(false),[privacy,setPrivacy]=useState(false),[enquiry,setEnquiry]=useState(null),[rotation,setRotation]=useState(0),[zoom,setZoom]=useState(1),[intro,setIntro]=useState(()=>{try{return location.pathname==='/'&&!sessionStorage.getItem('afrah-story-seen')&&!matchMedia('(prefers-reduced-motion: reduce)').matches}catch{return false}}),[saved,setSaved]=useState(()=>{try{const value=JSON.parse(localStorage.getItem('afrah-saved')||'[]');return Array.isArray(value)?value:[]}catch{return[]}});
 const root=useRef(),smooth=useRef(),progressBar=useRef();const overlay=menu||film||map||privacy||enquiry!==null||intro;
 const done=useCallback(()=>{setIntro(false);try{sessionStorage.setItem('afrah-story-seen','1')}catch{}},[]);
 const navigate=useCallback(to=>{setMenu(false);if(to===location.pathname){smooth.current?.scrollTo(0,{duration:1});window.scrollTo({top:0,behavior:'smooth'});return}history.pushState({},'',to);setPath(to);},[]);
 useEffect(()=>{const pop=()=>{setMenu(false);setPath(location.pathname.replace(/\/$/,'')||'/')};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 useLayoutEffect(()=>{window.scrollTo({top:0,behavior:'instant'});document.title=`AFRAH — ${titles[path]||'Journal'}`;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let tick;
  if(!reduced){const l=new Lenis({lerp:.095,smoothWheel:true,anchors:true});smooth.current=l;l.on('scroll',ScrollTrigger.update);tick=t=>l.raf(t*1000);gsap.ticker.add(tick);if(overlay)l.stop()}
  const context=gsap.context(()=>{ScrollTrigger.create({start:0,end:'max',onUpdate:self=>{if(progressBar.current)progressBar.current.style.transform=`scaleX(${self.progress})`}});if(!reduced){gsap.utils.toArray('.s-reveal').forEach(e=>gsap.from(e,{y:55,opacity:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:e,start:'top 93%',once:true}}));gsap.utils.toArray('.s-word-reveal').forEach(e=>gsap.fromTo(e.children,{opacity:.24},{opacity:1,stagger:.07,ease:'none',scrollTrigger:{trigger:e,start:'top 80%',end:'bottom 55%',scrub:.8}}));gsap.utils.toArray('.s-image-drift').forEach(e=>gsap.fromTo(e.querySelector('img'),{yPercent:-5,scale:1.12},{yPercent:5,scale:1.12,ease:'none',scrollTrigger:{trigger:e,start:'top bottom',end:'bottom top',scrub:1}}));gsap.utils.toArray('.s-layer-building').forEach(e=>gsap.fromTo(e,{yPercent:12},{yPercent:0,ease:'none',scrollTrigger:{trigger:e.parentElement,start:'top bottom',end:'center center',scrub:1.1}}));gsap.utils.toArray('.s-stepped-media').forEach(e=>gsap.fromTo(e,{clipPath:'polygon(0 20%,33% 20%,33% 10%,66% 10%,66% 0,100% 0,100% 100%,0 100%)'},{clipPath:'polygon(0 0,33% 0,33% 0,66% 0,66% 0,100% 0,100% 100%,0 100%)',scrollTrigger:{trigger:e,start:'top 90%',end:'top 20%',scrub:1}}));}},root);
  const timer=setTimeout(()=>{ScrollTrigger.refresh();root.current?.querySelector('h1')?.focus({preventScroll:true})},100);document.fonts.ready.then(()=>ScrollTrigger.refresh());return()=>{clearTimeout(timer);context.revert();if(tick)gsap.ticker.remove(tick);smooth.current?.destroy();smooth.current=null};
 },[path]);
 useEffect(()=>{if(overlay){smooth.current?.stop();document.body.style.overflow='hidden'}else{smooth.current?.start();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[overlay]);
 function toggleSave(id){setSaved(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];try{localStorage.setItem('afrah-saved',JSON.stringify(next))}catch{}return next})}
 return <StoryContext.Provider value={{navigate,saved,toggleSave,setEnquiry,setFilm,setMap}}><div className="story-app" ref={root}>
  <a href="#main-content" className="s-skip">Skip to content</a>
  <header className="s-header"><Link to="/" className="s-brand" aria-label="AFRAH home">AFRAH<span>®</span></Link><div className="s-header-current"><span className="s-status-dot"/>{titles[path]||'Journal'}</div><nav aria-label="Primary"><Link to="/residences">RESIDENCES</Link><Link to="/contact">LET’S TALK <ArrowUpRight size={14}/></Link><button onClick={()=>setMenu(true)} aria-label="Open menu"><span>MENU</span><Menu size={19}/></button></nav><i ref={progressBar} className="s-reading-progress"/></header>
  <main id="main-content" key={path} className="s-route-page">{page(path)}</main>
  <footer className="s-footer s-pad"><div className="s-footer-top"><Label>THE STORY CONTINUES WITH YOU.</Label><Link to="/contact">LET’S BEGIN.<ArrowUpRight/></Link></div><div className="s-footer-links"><div><Label>A DIFFERENT NATURE.</Label><p>A dialogue between<br/>architecture and life.</p></div><nav aria-label="Footer">{chapters.map(([p,t])=><Link to={p} key={p}>{t}</Link>)}<Link to="/contact">Contact</Link></nav><div><button onClick={()=>setPrivacy(true)}>Privacy <ArrowUpRight size={13}/></button><button onClick={()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}>Back to top ↑</button></div></div><div className="s-footer-brand" aria-hidden="true">AFRAH</div><div className="s-footer-bottom"><Label>© {new Date().getFullYear()} AFRAH</Label><Label>FORM / NATURE / HUMAN</Label><Label>IMAGINE WHAT COMES NEXT.</Label></div></footer>
  {intro&&<Intro done={done}/>}
  {menu&&<Dialog title="Explore AFRAH" className="s-menu-dialog" onClose={()=>setMenu(false)}><div className="s-menu-intro"><Link to="/" className="s-brand">AFRAH®</Link><Media src="/story/idea-detail.webp" alt="Architecture in light and shadow"/><Label>ONE STORY. MANY PERSPECTIVES.</Label></div><nav aria-label="All pages">{[['/','Home','00'],...chapters,['/contact','Contact','07']].map(([p,t,n])=><Link to={p} key={p} aria-current={path===p?'page':undefined}><sup>{n}</sup>{t}<ArrowUpRight/></Link>)}</nav></Dialog>}
  {enquiry!==null&&<Enquiry residence={enquiry||null} onClose={()=>setEnquiry(null)}/>}
  {film&&<Dialog title="AFRAH film" className="s-film-dialog" onClose={()=>setFilm(false)}><video controls autoPlay playsInline poster="/media/living.webp" src="/media/afrah-life.mp4"/><Label>AFRAH / LIFE, UNHURRIED.</Label></Dialog>}
  {map&&<Dialog title="Architectural model" className="s-model-dialog" onClose={()=>setMap(false)}><Label>AFRAH / AN ARCHITECTURAL STUDY</Label><h2>A different<br/>perspective.</h2><Suspense fallback={<img src="/era/residenceTowers.webp" alt="Architectural model loading"/>}><City rotation={rotation} zoom={zoom} monochrome/></Suspense><div className="s-model-tools"><button className="s-circle" aria-label="Rotate left" onClick={()=>setRotation(v=>v-.25)}><ChevronLeft/></button><button className="s-circle" aria-label="Rotate right" onClick={()=>setRotation(v=>v+.25)}><ChevronRight/></button><button className="s-circle" aria-label="Zoom out" disabled={zoom<=.6} onClick={()=>setZoom(v=>Math.max(.6,v-.2))}><Minus/></button><button className="s-circle" aria-label="Zoom in" disabled={zoom>=1.8} onClick={()=>setZoom(v=>Math.min(1.8,v+.2))}><Plus/></button></div></Dialog>}
  {privacy&&<Dialog title="Privacy" className="s-privacy-dialog" onClose={()=>setPrivacy(false)}><Label>YOUR INFORMATION</Label><h2>In confidence.</h2><p>Saved residences stay in this browser. Enquiries are stored privately on the local server. No advertising trackers are used and your details are not sent to external marketing services.</p></Dialog>}
 </div></StoryContext.Provider>
}
